### ISSUE TITLE
Generate UUID for payments

### ISSUE THREAD

**Issue by stinovlas** [stinovlas/django-pain#15]
Add field `uuid` of type [`UUIDField`](https://docs.djangoproject.com/en/dev/ref/models/fields/#django.db.models.UUIDField) to `BankPayment` model in order to generate nice unique identifier for each payment. Values will be generated by `uuid.uuid4()` function.

This identifier will be used by payment processors in communication with various systems to prevent data mismatch in case of broken connection or other unexpected events.

**Comment by tpazderka** [comment]
LGTM
